name: 'My Composite Action'
description: 'This is a composite action that runs multiple steps'
inputs:
  environment:
    description: 'The environment to deploy to'
    required: true
    default: 'staging'

runs:
  using: 'composite'
  steps:
    - name: Set up environment
      run: |
        echo "Setting up environment: ${{ inputs.environment }}"
    
    - name: Install dependencies
      run: npm install
    
    - name: Run tests
      run: npm test

    - name: Deploy to environment
      run: echo "Deploying to ${{ inputs.environment }} environment"
