name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy-env:
    uses: ./.github/workflows/calledworkflow.yml
    permissions:
      actions: read
      contents: write
      id-token: write

