name: LogReader deployment workflow

on:
  workflow_call:  
jobs:
  deploy-env:
    name: "Deploy LogReader"    
    runs-on: ubuntu-latest    
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checkout Source"
        uses: actions/checkout@v4
      
