name: "Build & Security"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  Build:
    name: Analyze
    runs-on: 'ubuntu-latest'
    timeout-minutes: 120
    permissions:
      actions: read
      contents: read
      security-events: write
      packages: read
      id-token: write
      checks: write
    strategy:
      fail-fast: false
      matrix:
        language: ['csharp', 'javascript']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Build the Code
        run: dotnet build  # replace this with your build command

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8

      # Greeting and random number generation
      - name: Set Greeting
        run: echo "Hello ${{ inputs.who-to-greet }}."
        shell: bash
        env:
          who-to-greet: ${{ inputs.who-to-greet }}                    
      - name: Random Number Generator
        id: random-number-generator
        run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_ENV
        shell: bash

      - name: Set GitHub Path
        run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
        shell: bash
        env:
          GITHUB_ACTION_PATH: ${{ github.action_path }}
          
      - name: Upload CodeQL results for code scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ github.workspace }}/codeql-results.sarif

      - name: Run goodbye.sh
        run: |
          if [ -f "goodbye.sh" ]; then
            bash goodbye.sh
          else
            echo "goodbye.sh not found!"
          fi
        shell: bash
