name: 'Security Analysis Workflow'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
        inputs:
            ReleaseTag:
                required: true
                type: string
            environment:
                default: "dev"
                required: false
                type: string
            region:
                default: "us-east-1"
                required: false
                type: string
            toDeploy: 
                required: true
                type: string 
  
jobs: 
  security:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: 'Checkout code'
        uses: actions/checkout@v3

      # Step 2: Run the composite action
      - name: 'Run security scan with GHAS tools'
        uses: ./.github/actions/my-composite-action
        with:
          repo-token: 'TestToken'
          
  ReadJob:
        uses: ./.github/workflows/common.deploy.read.yml
        with:
            ReleaseTag: ${{inputs.ReleaseTag}}
            environment: ${{inputs.environment}}
            region: ${{inputs.region}}
            toDeploy: ${{inputs.toDeploy}}
        secrets: inherit
