name: 'Security Analysis Workflow'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: 'Checkout code'
        uses: actions/checkout@v3

      # Step 2: Run the composite action
      - name: 'Run security scan with GHAS tools'
        uses: ./.github/actions/my-composite-action
        with:
          repo-token: 'TestToken'
          
      #${{ secrets.GITHUB_TOKEN }}
